config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts
  resources :articles
  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :cell, optional: true
  belongs_to :directorship, optional: true
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :skills
  has_many :articles
  has_many :posts 
  has_many :article_comments
  has_many :post_comments
  has_many :directorship_tasks
  has_many :cell_tasks


  enum kind: { 
    member: 0,
    gp_director: 1,
    director: 2,
    project_director: 3,
    pmo_manager: 4,
    cell_manager: 5
}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :skilltree]
  before_action :allow_only_gp, only: [:new, :create]
  before_action :set_cells, only: [:new, :edit]
  before_action :set_directorships, only: [:new, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    ongoing_projects = Project.where(status: false)
    @user_projects = []
    ongoing_projects.each do |proj|
      if proj.users_id.include?(current_user.id)
        @user_projects.push(proj)
      end
    end
    @user_ex_projects = []
    finished_prjects = Project.where(status: true)
    finished_prjects.each do |proj|
      if proj.users_id.include?(current_user.id)
        @user_ex_projects.push(proj)
      end
    end

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = '1234567'
    @user.password_confirmation = '1234567'
    if @user.save 
      redirect_to root_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def skilltree
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :kind, :cell_id, :directorship_id)
    end

    def allow_only_gp
      unless current_user.kind == 'gp_director'
        redirect_to root_path
      end
    end

    def set_cells
      @cells = []
      Cell.all.each do |cell|
        aux = [cell.name, cell.id]
        @cells.push(aux)
      end
    end

    def set_directorships
      @directorships = []
      Directorship.all.each do |dir|
        aux = [dir.name, dir.id]
        @directorships.push(aux)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  Tipo de usuário:
  <%= select(:user, :kind, [
    ['Assessor', 'member'],
    ['Diretor de GP', 'gp_director'],
    ['Diretor', 'director'],
    ['Diretor de Projeto', 'project_director'],
    ['Gerente de PMO', 'pmo_manager'],
    ['Gerente de celula', 'cell_manager']
  ]) %>
  <br/>


  Célula:
  <%= select(:user, :cell_id, cells) %>

  <br/>
  Diretoria:
  <%= select(:user, :directorship_id, dirs) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.kind %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user, cells: @cells, dirs: @directorships  %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @user.kind %>
</p>

<p>
  <strong>Célula atual:</strong>
  <%= @user.cell.name %>
</p>

<p>
  <strong>Directoria atual:</strong>
  <%= @user.directorship.name %>
</p>

<h4>Projetos em Andamento:</h4>
<table>
  <thead>
    <th>Projeto</th>
    <th>Descrição</th>
    <th>Criado em</th>
  <thead>
  <tbody>
    <% @user_projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.created_at %></td>
      </tr>
    <%end%>
  </tbody>
</table>

<h4>Projetos já Acabados:</h4>
<table>
  <thead>
    <th>Projeto</th>
    <th>Descrição</th>
    <th>Criado em</th>
  <thead>
  <tbody>
    <% @user_ex_projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.created_at %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<br/>

<%= link_to  "Arvore de habilidade", skilltree_path(:id => @user.id) %>

<br/>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/skilltree.html.erb
<h1>Árvore de Habilidades de <%= @user.name %></h1>


<table>
    <thead>
        <th>Habilidade</th>
        <th>Descrição</th>
    </thead>
    <tbody>
        <% @user.skills.each do |skill| %>
            <tr>
                <td><%= skill.name %></td>
                <td><%= skill.description %></td>
            </tr>
        <%end%>
    </tbody>
</table>

<br/>

<%= link_to  "Voltar", @user %> | 
<% if current_user == @user %>
    <%= link_to  "Adicionar Habilidade", new_skill_path(:id => @user.id) %>
<%end%>