config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts
  resources :articles
  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/directorship.rb
class Directorship < ApplicationRecord
    has_many :directorship_goals
    has_many :cells
    has_many :users
end

app/controllers/directorships_controller.rb
class DirectorshipsController < ApplicationController
  before_action :set_directorship, only: [:show, :edit, :update, :destroy]
  before_action :set_directors, only: [:new, :edit]

  # GET /directorships
  # GET /directorships.json
  def index
    @directorships = Directorship.all
  end


  # GET /directorships/1
  # GET /directorships/1.json
  def show
    @users = User.all
  end

  # GET /directorships/new
  def new
    @directorship = Directorship.new
  end

  # GET /directorships/1/edit
  def edit
  end

  # POST /directorships
  # POST /directorships.json
  def create
    @directorship = Directorship.new(directorship_params)

    respond_to do |format|
      if @directorship.save
        format.html { redirect_to @directorship, notice: 'Directorship was successfully created.' }
        format.json { render :show, status: :created, location: @directorship }
      else
        format.html { render :new }
        format.json { render json: @directorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directorships/1
  # PATCH/PUT /directorships/1.json
  def update
    respond_to do |format|
      if @directorship.update(directorship_params)
        format.html { redirect_to @directorship, notice: 'Directorship was successfully updated.' }
        format.json { render :show, status: :ok, location: @directorship }
      else
        format.html { render :edit }
        format.json { render json: @directorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directorships/1
  # DELETE /directorships/1.json
  def destroy
    @directorship.destroy
    respond_to do |format|
      format.html { redirect_to directorships_url, notice: 'Directorship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directorship
      @directorship = Directorship.find(params[:id])
    end

    def set_directors
      @directors = []
      User.where(kind: 'director').each do |director|
        aux = [director.name, director.id]
        @directors.push(aux)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directorship_params
      params.require(:directorship).permit(:name, :director)
    end
end

app/helpers/directorships_helper.rb
module DirectorshipsHelper
end

app/views/directorships/_form.html.erb
<%= form_with(model: directorship, local: true) do |form| %>
  <% if directorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(directorship.errors.count, "error") %> prohibited this directorship from being saved:</h2>

      <ul>
      <% directorship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.select :director, directors %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/directorships/edit.html.erb
<h1>Editing Directorship</h1>

<%= render 'form', directorship: @directorship, directors: @directors %>

<%= link_to 'Show', @directorship %> |
<%= link_to 'Back', directorships_path %>

app/views/directorships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Directorships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Director</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directorships.each do |directorship| %>
      <tr>
        <td><%= directorship.name %></td>
        <% unless directorship.director.nil? %>
          <td><%= User.find(directorship.director).name %></td>
        <%else%>
          <td></td>
        <%end%>
        <td><%= link_to 'Show', directorship %></td>
        <td><%= link_to 'Edit', edit_directorship_path(directorship) %></td>
        <td><%= link_to 'Destroy', directorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directorship', new_directorship_path %>

app/views/directorships/new.html.erb
<h1>New Directorship</h1>

<%= render 'form', directorship: @directorship, directors: @directors %>

<%= link_to 'Back', directorships_path %>

app/views/directorships/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @directorship.name %>
</p>

<p>
  <strong>Director:</strong>
  <%= User.find(@directorship.director).name %>
</p>

<% @directorship.directorship_goals.each do |goal| %>
  <%= goal.title %> |
  <%= goal.status %> |
  <%= goal.description %> |
  <%= link_to 'Pagina da meta', show_directorshipgoal_path(:id => goal.id) %>
  <table>
    <thead>
      <th>Tarefa:</th>
      <th>Status:</th>
      <th>Designada a:</th>
    </thead>
    <% goal.directorship_tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.user.name %></td>
      </tr>
    <%end%>
  <table>
<%end%>

<%= link_to  "Criar nova Meta", directorshipgoal_path(:id => @directorship.id) %>

<%= link_to 'Edit', edit_directorship_path(@directorship) %> |
<%= link_to 'Back', directorships_path %>