config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts
  resources :articles
  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :directorship
  has_many :users
  has_many :cell_goals
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: [:show, :edit, :update, :destroy]
  before_action :set_managers, only: [:new, :edit]
  before_action :set_directorships, only: [:new, :edit]

  # GET /cells
  # GET /cells.json
  def index
    @cells = Cell.all
  end


  # GET /cells/1
  # GET /cells/1.json
  def show
    @users = User.all
  end

  # GET /cells/new
  def new
    @cell = Cell.new
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells
  # POST /cells.json
  def create
    @cell = Cell.new(cell_params)

    respond_to do |format|
      if @cell.save
        format.html { redirect_to @cell, notice: 'Cell was successfully created.' }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1
  # PATCH/PUT /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to @cell, notice: 'Cell was successfully updated.' }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1
  # DELETE /cells/1.json
  def destroy
    @cell.destroy
    respond_to do |format|
      format.html { redirect_to cells_url, notice: 'Cell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find(params[:id])
    end

    def set_managers
      @managers = []
      User.where(kind: "cell_manager").each do |manager|
        aux = [manager.name, manager.id]
        @managers.push(aux)
      end
    end

    def set_directorships
      @directorships = []
      Directorship.all.each do |dir|
        aux = [dir.name, dir.id]
        @directorships.push(aux)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cell_params
      params.require(:cell).permit(:name, :manager, :directorship_id)
    end
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/views/cells/_form.html.erb
<%= form_with(model: cell, local: true) do |form| %>
  <% if cell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
      <% cell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.select :manager, managers %>
  </div>

  <div class="field">
    <%= form.label :directorship_id %>
    <%= form.select :directorship_id, dirs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<h1>Editing Cell</h1>

<%= render 'form', cell: @cell, managers: @managers, dirs: @directorships %>

<%= link_to 'Show', @cell %> |
<%= link_to 'Back', cells_path %>

app/views/cells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cells</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manager</th>
      <th>Directorship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cells.each do |cell| %>
      <tr>
        <td><%= cell.name %></td>
        <td><%= cell.manager %></td>
        <td><%= cell.directorship.name %></td>
        <td><%= link_to 'Show', cell %></td>
        <td><%= link_to 'Edit', edit_cell_path(cell) %></td>
        <td><%= link_to 'Destroy', cell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cell', new_cell_path %>

app/views/cells/new.html.erb
<h1>New Cell</h1>

<%= render 'form', cell: @cell, managers: @managers, dirs: @directorships %>

<%= link_to 'Back', cells_path %>

app/views/cells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cell.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= User.find(@cell.manager).name %>
</p>

<p>
  <strong>Directorship:</strong>
  <%= @cell.directorship.name %>
</p>

<table>
  <th>Integrantes</th>
  <% @cell.users.each do |user| %>
    <tr><%= link_to user.name, user %></tr>
  <%end%>
</table>


<% @cell.cell_goals.each do |goal| %>
  <%= goal.title %> |
  <%= goal.status %> |
  <%= goal.description %> |
  <%= link_to 'Pagina da meta', show_cellgoal_path(:id => goal.id) %>
  <table>
    <thead>
      <th>Tarefa:</th>
      <th>Status:</th>
      <th>Designada a:</th>
    </thead>
    <% goal.cell_tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.user.name %></td>
      </tr>
    <%end%>
  <table>
<%end%>

<%= link_to  "Criar nova Meta", cellgoal_path(:id => @cell.id) %>

<%= link_to 'Edit', edit_cell_path(@cell) %> |
<%= link_to 'Back', cells_path %>