config/routes.rb
Rails.application.routes.draw do

  post 'users', to: 'users#create'
  devise_for :users
  root to: 'pages#home'

  post '/newcellgoaltask', to: 'cell_goal#createTask', as: 'new_cell_task'
  get '/newcellgoal', to: 'cell_goal#new', as: 'cellgoal'
  post '/newcellgoal', to: 'cell_goal#create', as: 'create_cellgoal'
  get '/showcellgoal', to: 'cell_goal#show', as: 'show_cellgoal'

  post '/newdirectorshipgoaltask', to: 'directorship_goals#createTask', as: 'new_directorship_task'
  get '/newdirectorshipgoal', to: 'directorship_goals#new', as: 'directorshipgoal'
  post '/newdirectorshipgoal', to: 'directorship_goals#create', as: 'create_directorshipgoal'
  get '/showdirectorshipgoal', to: 'directorship_goals#show', as: 'show_directorshipgoal'

  get '/skilltree', to: 'users#skilltree', as: 'skilltree'

  resources :users
  resources :posts
  resources :articles
  resources :skills

  resources :projects
  resources :cells
  resources :directorships
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user = User.new

    if user.kind == 'member'
      can :read, :create, Article
      can :read, :create, ArticleComment
      can :read, :create, Post
      can :read, :create, PostComment
      can :update, DirectorshipTask
      can :update, CellTask
      can :read, Directorship
      can :read, Cell
    end

    if user.kind == 'director'
      can :manage, Article
      can :manage, Post
      can :manage, PostComment
      can :manage, Directorship
      can :manage, DirectorshipGoal
      can :manage, DirectorshipTask
      can :manage, Cell
    end

    if user.kind == 'cell_manager'
      can :manage, Article
      can :manage, ArticleComment
      can :manage, Post
      can :manage, PostComment
      can :update, DirectorshipTask
      can :read, Directorship
      can :manage, Cell
      can :manage, CellGoal
      can :manage, CellTask
    end

    if user.kind == 'gp_director'
      can :manage, Article
      can :manage, ArticleComment
      can :manage, Post
      can :manage, PostComment
      can :update, DirectorshipTask
      can :read, Directorship
      can :manage, Cell
      can :manage, CellGoal
      can :manage, CellTask
      can :manage, User
    end

    if user.kind == 'pmo_manager'
      can :manage, Article
      can :manage, ArticleComment
      can :manage, Post
      can :manage, PostComment
      can :update, DirectorshipTask
      can :read, Directorship
      can :manage, Cell
      can :manage, CellGoal
      can :manage, CellTask
      can :manage, Project
    end

    if user.kind == 'project_director'
      can :manage, Article
      can :manage, ArticleComment
      can :manage, Post
      can :manage, PostComment
      can :update, DirectorshipTask
      can :manage, Directorship
      can :manage, DirectorshipGoal
      can :manage, Cell
      can :manage, CellGoal
      can :manage, CellTask
      can :manage, Project
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_comments
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :directorship
  has_many :users
  has_many :cell_goals
end

app/models/cell_goal.rb
class CellGoal < ApplicationRecord
  belongs_to :cell
  has_many :cell_tasks
end

app/models/cell_task.rb
class CellTask < ApplicationRecord
  belongs_to :cell_goal
  belongs_to :user
end

app/models/directorship.rb
class Directorship < ApplicationRecord
    has_many :directorship_goals
    has_many :cells
    has_many :users
end

app/models/directorship_goal.rb
class DirectorshipGoal < ApplicationRecord
  belongs_to :directorship
  has_many :directorship_tasks
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :project_users
    has_many :users, through: :project_users
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :cell, optional: true
  belongs_to :directorship, optional: true
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :skills
  has_many :articles
  has_many :posts 
  has_many :article_comments
  has_many :post_comments
  has_many :directorship_tasks
  has_many :cell_tasks


  enum kind: { 
    member: 0,
    gp_director: 1,
    director: 2,
    project_director: 3,
    pmo_manager: 4,
    cell_manager: 5
}
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto final</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if user_signed_in? %>
<<<<<<< HEAD
        <header>
          <nav>
            <%= link_to  "Perfil", current_user %>
            <%= link_to  "Fórum", posts_path %>
            <%= link_to  "Artigos", articles_path %>
            <% if current_user.kind == 'cell_manager' || 'pmo_manager' %>
              <%= link_to  "Células", cells_path %>
            <%end%>
            <% if current_user.kind == 'director' || 'project_director' || 'gp_director' %>
              <%= link_to  "Diretorias", directorships_path %>
              <%= link_to  "Células", cells_path %>
            <%end%>
            <% if current_user.kind == 'gp_director' %>
              <%= link_to  "Usuários", users_path %>
            <%end%>
            <% if current_user.kind == 'pmo_manager' || 'project_director' %>
              <%= link_to  "Projetos", projects_path %>
            <%end%>
          </nav>
        </header>
=======
        <nav>



          <%= link_to  "Perfil", current_user %>
          <%= link_to  "Fórum", posts_path %>
          <%= link_to  "Artigos", articles_path %>
          <% if current_user.kind == 'cell_manager' || 'pmo_manager' %>
            <%= link_to  "Células", cells_path %>
          <%end%>
          <% if current_user.kind == 'director' || 'project_director' || 'gp_director' %>
            <%= link_to  "Diretorias", directorships_path %>
            <%= link_to  "Células", cells_path %>
          <%end%>
          <% if current_user.kind == 'gp_director' %>
            <%= link_to  "Usuários", users_path %>
          <%end%>
          <% if current_user.kind == 'pmo_manager' || 'project_director' %>
            <%= link_to  "Projetos", projects_path %>
          <%end%>
        </nav>
>>>>>>> 2d0bb8961dc83f5a46baf555ee5e64ff67e1fb70
      <%end%>
    <% if user_signed_in? %>
      <%= link_to  "Log-out", destroy_user_session_path(current_user.id), method: :delete %>
    <%end%>


    <div class="navbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <%= image_tag("menu-button.svg", size: "30x30", :alt => "Menu")%>
          </button>
          <a class="navbar-brand" href="#">

            <%= image_tag("logo-branca.png", size: "60x40", :alt => "Logo InJunior") %>
          </a>
        </div>
        <div class="navbar-collapse collapse" id="navbarToggler">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="#">Artigos</a>
            </li>
            <li>
              <a href="#">Fórum</a>
            </li>
            <li>
              <a href="#">Projetos</a>
            </li>
            <li>
              <a href="#">Diretoria</a>
            </li>
            <li>
              <a href="#">Células</a>
            </li>
            <li class="nav-item-profile">
              <a href="#">
                <%= image_tag("image-profile-white.png", size: "30x30", :alt => "Perfil do usuário") %>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>


    <%= yield %>

    <footer>


    <div class="containeir">

      <div class="row">

        <div class="col-sm-8">
          <ul class="text-center">
            <li>
              <a href="#">Artigos</a>
            </li>
            <li>
              <a href="#">Fórum</a>
            </li>
            <li>
              <a href="#">Projetos</a>
            </li>
            <li>
              <a href="#">Diretorias</a>
            </li>
            <li>
              <a href="#">Células</a>
            </li>
          
        </div>
        <div class="col-sm-4">
          <%= image_tag 'logo-branca.png', id: 'img-logo', class: 'img-responsive' %>

        </div>
      </div>

      <div class="footer-copyright text-center">
        <p>Copyright © 2019 Feito com <3 e vários códigos | Grupo 2</p>
      </div>
    </div>
    </footer>

    <a href="#" class="go-top"><%= image_tag 'up-arrow.svg', class: 'img-responsive' %></a>
    
  </body>
</html>